### PR TITLE
Dev server should serve also the SPID IDP logo

### PR DESCRIPTION
**Pull request by Undermaken**
This PR returns the list of the SPID idp by updating the logo url as a local resource

### CODE REVIEW

**Review by debiff — COMMENTED** [review]
LGTM but I don't understand why do you add all the unused images in the `assets/spid/idps..` directory.

**Comment by Undermaken** [comment]
> LGTM but I don't understand why do you add all the unused images in the `assets/spid/idps..` directory.

These images are dynamically returned by the server when the clients ask for a specific IDP

`src/routers/services_metadata.ts`

idp

**Comment by debiff** [comment]
> These images are dynamically returned by the server when the clients ask for a specific IDP
> 
> `src/routers/services_metadata.ts`
> 
> idp

But these images are not the same you added in this PR.
The images returned by the snippet you attach are in the `assets/imgs/logos/spid` path while the images you added are in `assets/spid/idps`. 
I've misunderstood something?

**Comment by Undermaken** [comment]
> > These images are dynamically returned by the server when the clients ask for a specific IDP
> > `src/routers/services_metadata.ts`
> > idp
> 
> But these images are not the same you added in this PR. The images returned by the snippet you attach are in the `assets/imgs/logos/spid` path while the images you added are in `assets/spid/idps`. I've misunderstood something?

Yes, I know it is a little bit tricky
`image folder path !== requested logo`

This piece of code adds (injects) the logo url to the IDP list
Schermata 2022-03-01 alle 09 43 06

So when the clients asks for idp info 
`http://127.0.0.1:3000/static_contents/spid/idps/list.json`
the response is something like this
<details>
  <summary>Click to expand!</summary>

```json
{
   "items": [
      {
         "id": "arubaid",
         "name": "Aruba",
         "logo": "http://192.168.1.77:3000/static_contents/logos/spid/idps/spid-idp-arubaid.png",
         "profileUrl": "http://selfcarespid.aruba.it"
      },
      {
         "id": "infocertid",
         "name": "Infocert",
         "logo": "http://192.168.1.77:3000/static_contents/logos/spid/idps/spid-idp-infocertid.png",
         "profileUrl": "https://my.infocert.it/selfcare"
      },
      {
         "id": "intesaid",
         "name": "Intesa",
         "logo": "http://192.168.1.77:3000/static_contents/logos/spid/idps/spid-idp-intesaid.png",
         "profileUrl": "https://spid.intesa.it"
      },
      {
         "id": "lepidaid",
         "name": "Lepida",
         "logo": "http://192.168.1.77:3000/static_contents/logos/spid/idps/spid-idp-lepidaid.png",
         "profileUrl": "https://id.lepida.it/"
      },
      {
         "id": "namirialid",
         "name": "Namirial",
         "logo": "http://192.168.1.77:3000/static_contents/logos/spid/idps/spid-idp-namirialid.png",
         "profileUrl": "https://idp.namirialtsp.com/idp"
      },
      {
         "id": "posteid",
         "name": "Poste",
         "logo": "http://192.168.1.77:3000/static_contents/logos/spid/idps/spid-idp-posteid.png",
         "profileUrl": "https://posteid.poste.it/private/cruscotto.shtml"
      },
      {
         "id": "sielteid",
         "name": "Sielte",
         "logo": "http://192.168.1.77:3000/static_contents/logos/spid/idps/spid-idp-sielteid.png",
         "profileUrl": "https://myid.sieltecloud.it/profile/"
      },
      {
         "id": "spiditalia",
         "name": "SPIDItalia Register.it",
         "logo": "http://192.168.1.77:3000/static_contents/logos/spid/idps/spid-idp-spiditalia.png",
         "profileUrl": "https://spid.register.it"
      },
      {
         "id": "timid",
         "name": "Telecom Italia",
         "logo": "http://192.168.1.77:3000/static_contents/logos/spid/idps/spid-idp-timid.png",
         "profileUrl": "https://id.tim.it/identity/private/"
      }
   ]
}
```
</details>

Instead, this piece of code returns the specific logo
i.e: `http://192.168.1.77:3000/static_contents/logos/spid/idps/spid-idp-arubaid.png`
by picking it from `assets/imgs/logos/spid` where I placed all the IDP logo images
Schermata 2022-03-01 alle 09 43 14

**Review by debiff — APPROVED** [review]

**Pull request merged**
