### PR TITLE
[IOBP-45,IOBP-75,IOBP-494] Remove Bonus Cashback, Bonus Vacanze and Sicilia Vola features

### PR DESCRIPTION
**Pull request by mastro993**
## Short description
This PR removes everything related to **Bonus Cashback**, **Bonus Vacanze** and **Sicilia Vola** features

## How to test
Tests should solve correclty

### CODE REVIEW

**Comment by forrest57** [comment]
while this PR gets the job done, there still are some --surely unused-- references of BPD and BV around the project.
Since this is an "internal" project, we could very well ignore this and keep going, but I'm not 100% on this; what do you think? @mastro993

**Comment by mastro993** [comment]
> while this PR gets the job done, there still are some --surely unused-- references of BPD and BV around the project. Since this is an "internal" project, we could very well ignore this and keep going, but I'm not 100% on this; what do you think? @mastro993

What are these references?

**Comment by forrest57** [comment]
> > while this PR gets the job done, there still are some --surely unused-- references of BPD and BV around the project. Since this is an "internal" project, we could very well ignore this and keep going, but I'm not 100% on this; what do you think? @mastro993
> 
> What are these references?

there still is the `bpd_ranking` field in `backend.ts`, also in `configDashboard.ts`; overall with a full project search, the `bpd` word pops up quite a bunch of time, even if used wrongly (101 in 17 files to be exact).
BV is referenced mainly in `specs_functions.yaml`, `bonus_available.json`, `public.ts`, `services_metadata.ts` and `variables.ts`, with a full search on `vacanze` around the app resulting in 64 results in 11 files.

As I already said, no biggie if we let it in, since it's all an "internal" thing, better to have a bit more than a bit less; but still if we fully want to remove those two I think those parts should be touched on.

**Comment by mastro993** [comment]
> 18a941e

See https://github.com/pagopa/io-dev-api-server/pull/343/commits/18a941e1e9602d6fb5b2b9cdccf2372c81500280

**Comment by mastro993** [comment]
> > > while this PR gets the job done, there still are some --surely unused-- references of BPD and BV around the project. Since this is an "internal" project, we could very well ignore this and keep going, but I'm not 100% on this; what do you think? @mastro993
> > 
> > 
> > What are these references?
> 
> there still is the `bpd_ranking` field in `backend.ts`, also in `configDashboard.ts`; overall with a full project search, the `bpd` word pops up quite a bunch of time, even if used wrongly (101 in 17 files to be exact). BV is referenced mainly in `specs_functions.yaml`, `bonus_available.json`, `public.ts`, `services_metadata.ts` and `variables.ts`, with a full search on `vacanze` around the app resulting in 64 results in 11 files.
> 
> As I already said, no biggie if we let it in, since it's all an "internal" thing, better to have a bit more than a bit less; but still if we fully want to remove those two I think those parts should be touched on.

See https://github.com/pagopa/io-dev-api-server/pull/343/commits/18a941e1e9602d6fb5b2b9cdccf2372c81500280

**Comment by forrest57** [comment]
@mastro993  almost done, bonusVacanze still pops up in `src/routers/public.ts`, line 152 and
for BPD we still have:
- `payloads/backend.ts`
- `walletsV2/configDashboard.ts`
- `walletsV2/index.ts`
- `walletsV2/methods/bancomat.ts`
- `utils/variables.ts` maybe? not sure about this one

once again, in some places "bpd" is just a buzzword that is thrown around, but still I think it should be at least renamed in order to completely remove BPD from the app/devServer.

also, by removing those you can remove a bunch of things, like the `resetProfile` handler, so we end up with an even tidier structure

**Comment by mastro993** [comment]
> @mastro993 almost done, bonusVacanze still pops up in `src/routers/public.ts`, line 152 and for BPD we still have:
> 
> * `payloads/backend.ts`
> * `walletsV2/configDashboard.ts`
> * `walletsV2/index.ts`
> * `walletsV2/methods/bancomat.ts`
> * `utils/variables.ts` maybe? not sure about this one
> 
> once again, in some places "bpd" is just a buzzword that is thrown around, but still I think it should be at least renamed in order to completely remove BPD from the app/devServer.
> 
> also, by removing those you can remove a bunch of things, like the `resetProfile` handler, so we end up with an even tidier structure

Liked you said, BPD (Bonus Pagamenti Digitali) is a word used to reference to everything related to bonuses (ID Pay, CGN, and so on...), it's not always linked to the Cashback bonus. ;) 

In those files BPD is used as flag to indicate if payment methods have BPD capabilities (like ID Pay).

**Review by forrest57 — APPROVED** [review]

**Pull request merged**
